version: '3'

services:
  redis:
    image: redis:alpine
    container_name: sd_qrman_redis
    restart: unless-stopped
    networks:
      - qrnet

  app:
    image: ghcr.io/semiodigital/qrman:latest
    container_name: sd_qrman_app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    volumes:
      - qrman_config:/app/config
      - ./.env:/app/.env.sys
      - ./.env.laravel:/app/.env
      - qrman_storage:/app/storage
    env_file:
      - .env
    networks:
      - qrnet
    ports:
      - 8000:8000

networks:
    qrnet:
        driver: bridge
        ipam:
            driver: default

volumes:
  qrman_config:
  qrman_storage:     
